export interface Pokemon {
  id: number;
  nombre: string;
  tipo: string[];
  habilidades: string[];
  habitat: 'Tierra' | 'Mar';
  hp: number;
  ataque: number;
  imagen: string;
  color: string;
}

export const LISTA_POKEMON: Pokemon[] = [
  // --- TIERRA (GROUND) ---
  {
    id: 27,
    nombre: 'Sandshrew',
    tipo: ['Tierra'],
    habilidades: ['Velo Arena', 'Ímpetu Arena'],
    habitat: 'Tierra',
    hp: 50,
    ataque: 75,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png',
  },
  {
    id: 28,
    nombre: 'Sandslash',
    tipo: ['Tierra'],
    habilidades: ['Velo Arena', 'Ímpetu Arena'],
    habitat: 'Tierra',
    hp: 75,
    ataque: 100,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png',
  },
  {
    id: 50,
    nombre: 'Diglett',
    tipo: ['Tierra'],
    habilidades: ['Velo Arena', 'Trampa Arena'],
    habitat: 'Tierra',
    hp: 10,
    ataque: 55,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png',
  },
  {
    id: 51,
    nombre: 'Dugtrio',
    tipo: ['Tierra'],
    habilidades: ['Velo Arena', 'Trampa Arena'],
    habitat: 'Tierra',
    hp: 35,
    ataque: 100,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png',
  },
  {
    id: 104,
    nombre: 'Cubone',
    tipo: ['Tierra'],
    habilidades: ['Cabeza Roca', 'Pararrayos'],
    habitat: 'Tierra',
    hp: 50,
    ataque: 50,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png',
  },
  {
    id: 105,
    nombre: 'Marowak',
    tipo: ['Tierra'],
    habilidades: ['Cabeza Roca', 'Pararrayos'],
    habitat: 'Tierra',
    hp: 60,
    ataque: 80,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png',
  },
  {
    id: 111,
    nombre: 'Rhyhorn',
    tipo: ['Tierra', 'Roca'],
    habilidades: ['Pararrayos', 'Cabeza Roca'],
    habitat: 'Tierra',
    hp: 80,
    ataque: 85,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png',
  },
  {
    id: 112,
    nombre: 'Rhydon',
    tipo: ['Tierra', 'Roca'],
    habilidades: ['Pararrayos', 'Cabeza Roca'],
    habitat: 'Tierra',
    hp: 105,
    ataque: 130,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png',
  },
  {
    id: 231,
    nombre: 'Phanpy',
    tipo: ['Tierra'],
    habilidades: ['Recogida', 'Velo Arena'],
    habitat: 'Tierra',
    hp: 90,
    ataque: 60,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/231.png',
  },
  {
    id: 232,
    nombre: 'Donphan',
    tipo: ['Tierra'],
    habilidades: ['Robustez', 'Velo Arena'],
    habitat: 'Tierra',
    hp: 90,
    ataque: 120,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/232.png',
  },
  {
    id: 328,
    nombre: 'Trapinch',
    tipo: ['Tierra'],
    habilidades: ['Trampa Arena', 'Corte Fuerte'],
    habitat: 'Tierra',
    hp: 45,
    ataque: 100,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/328.png',
  },
  {
    id: 383,
    nombre: 'Groudon',
    tipo: ['Tierra'],
    habilidades: ['Sequía'],
    habitat: 'Tierra',
    hp: 100,
    ataque: 150,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png',
  },
  {
    id: 443,
    nombre: 'Gible',
    tipo: ['Tierra', 'Dragón'],
    habilidades: ['Piel Tosca', 'Velo Arena'],
    habitat: 'Tierra',
    hp: 58,
    ataque: 70,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/443.png',
  },
  {
    id: 445,
    nombre: 'Garchomp',
    tipo: ['Tierra', 'Dragón'],
    habilidades: ['Piel Tosca', 'Velo Arena'],
    habitat: 'Tierra',
    hp: 108,
    ataque: 130,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png',
  },
  {
    id: 449,
    nombre: 'Hippopotas',
    tipo: ['Tierra'],
    habilidades: ['Chorro Arena'],
    habitat: 'Tierra',
    hp: 68,
    ataque: 72,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/449.png',
  },
  {
    id: 450,
    nombre: 'Hippowdon',
    tipo: ['Tierra'],
    habilidades: ['Chorro Arena'],
    habitat: 'Tierra',
    hp: 108,
    ataque: 112,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/450.png',
  },
  {
    id: 529,
    nombre: 'Drilbur',
    tipo: ['Tierra'],
    habilidades: ['Ímpetu Arena', 'Poder Arena'],
    habitat: 'Tierra',
    hp: 60,
    ataque: 85,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/529.png',
  },
  {
    id: 25,
    nombre: 'Pikachu',
    tipo: ['Eléctrico'],
    habilidades: ['Electricidad Estática', 'Pararrayos'],
    habitat: 'Tierra', // Lo ponemos en Tierra para que el interface no de error
    hp: 35,
    ataque: 55,
    color: '#F7D02C',
    imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
  },
  {
    id: 530,
    nombre: 'Excadrill',
    tipo: ['Tierra', 'Acero'],
    habilidades: ['Ímpetu Arena', 'Rompemoldes'],
    habitat: 'Tierra',
    hp: 110,
    ataque: 135,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/530.png',
  },
  {
    id: 645,
    nombre: 'Landorus',
    tipo: ['Tierra', 'Volador'],
    habilidades: ['Poder Arena', 'Intimidación'],
    habitat: 'Tierra',
    hp: 89,
    ataque: 125,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/645.png',
  },
  {
    id: 749,
    nombre: 'Mudbray',
    tipo: ['Tierra'],
    habilidades: ['Firmeza', 'Ritmo Propio'],
    habitat: 'Tierra',
    hp: 70,
    ataque: 100,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/749.png',
  },
  {
    id: 750,
    nombre: 'Mudsdale',
    tipo: ['Tierra'],
    habilidades: ['Firmeza', 'Fuerza Mental'],
    habitat: 'Tierra',
    hp: 100,
    ataque: 125,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/750.png',
  },
  {
    id: 843,
    nombre: 'Silicobra',
    tipo: ['Tierra'],
    habilidades: ['Expulsarena', 'Mudar'],
    habitat: 'Tierra',
    hp: 52,
    ataque: 57,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/843.png',
  },
  {
    id: 844,
    nombre: 'Sandaconda',
    tipo: ['Tierra'],
    habilidades: ['Expulsarena', 'Mudar'],
    habitat: 'Tierra',
    hp: 72,
    ataque: 107,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/844.png',
  },
  {
    id: 901,
    nombre: 'Ursaluna',
    tipo: ['Tierra', 'Normal'],
    habilidades: ['Agallas', 'Pararrayos'],
    habitat: 'Tierra',
    hp: 130,
    ataque: 140,
    color: '#E2BF65',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/901.png',
  },
  {
    id: 964,
    nombre: 'Palafin',
    tipo: ['Agua'],
    habilidades: ['Cambio Heroico'],
    habitat: 'Mar',
    hp: 100,
    ataque: 70,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/964.png',
  },

  // --- MAR (WATER) ---
  {
    id: 7,
    nombre: 'Squirtle',
    tipo: ['Agua'],
    habilidades: ['Torrente', 'Cura Lluvia'],
    habitat: 'Mar',
    hp: 44,
    ataque: 48,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
  },
  {
    id: 8,
    nombre: 'Wartortle',
    tipo: ['Agua'],
    habilidades: ['Torrente', 'Cura Lluvia'],
    habitat: 'Mar',
    hp: 59,
    ataque: 63,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png',
  },
  {
    id: 9,
    nombre: 'Blastoise',
    tipo: ['Agua'],
    habilidades: ['Torrente', 'Cura Lluvia'],
    habitat: 'Mar',
    hp: 79,
    ataque: 83,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
  },
  {
    id: 54,
    nombre: 'Psyduck',
    tipo: ['Agua'],
    habilidades: ['Humedad', 'Aclimatación'],
    habitat: 'Mar',
    hp: 50,
    ataque: 52,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png',
  },
  {
    id: 55,
    nombre: 'Golduck',
    tipo: ['Agua'],
    habilidades: ['Humedad', 'Aclimatación'],
    habitat: 'Mar',
    hp: 80,
    ataque: 82,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png',
  },
  {
    id: 60,
    nombre: 'Poliwag',
    tipo: ['Agua'],
    habilidades: ['Absorbe Agua', 'Ritmo Propio'],
    habitat: 'Mar',
    hp: 40,
    ataque: 50,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png',
  },
  {
    id: 62,
    nombre: 'Poliwrath',
    tipo: ['Agua', 'Lucha'],
    habilidades: ['Absorbe Agua', 'Humedad'],
    habitat: 'Mar',
    hp: 90,
    ataque: 95,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png',
  },
  {
    id: 72,
    nombre: 'Tentacool',
    tipo: ['Agua', 'Veneno'],
    habilidades: ['Cuerpo Puro', 'Lodo Líquido'],
    habitat: 'Mar',
    hp: 40,
    ataque: 40,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png',
  },
  {
    id: 73,
    nombre: 'Tentacruel',
    tipo: ['Agua', 'Veneno'],
    habilidades: ['Cuerpo Puro', 'Lodo Líquido'],
    habitat: 'Mar',
    hp: 80,
    ataque: 70,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png',
  },
  {
    id: 86,
    nombre: 'Seel',
    tipo: ['Agua'],
    habilidades: ['Sebo', 'Hidratación'],
    habitat: 'Mar',
    hp: 65,
    ataque: 45,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png',
  },
  {
    id: 87,
    nombre: 'Dewgong',
    tipo: ['Agua', 'Hielo'],
    habilidades: ['Sebo', 'Hidratación'],
    habitat: 'Mar',
    hp: 90,
    ataque: 70,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png',
  },
  {
    id: 90,
    nombre: 'Shellder',
    tipo: ['Agua'],
    habilidades: ['Caparazón', 'Encadenado'],
    habitat: 'Mar',
    hp: 30,
    ataque: 65,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png',
  },
  {
    id: 91,
    nombre: 'Cloyster',
    tipo: ['Agua', 'Hielo'],
    habilidades: ['Caparazón', 'Encadenado'],
    habitat: 'Mar',
    hp: 50,
    ataque: 95,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png',
  },
  {
    id: 98,
    nombre: 'Krabby',
    tipo: ['Agua'],
    habilidades: ['Corte Fuerte', 'Caparazón'],
    habitat: 'Mar',
    hp: 30,
    ataque: 105,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png',
  },
  {
    id: 99,
    nombre: 'Kingler',
    tipo: ['Agua'],
    habilidades: ['Corte Fuerte', 'Caparazón'],
    habitat: 'Mar',
    hp: 55,
    ataque: 130,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png',
  },
  {
    id: 116,
    nombre: 'Horsea',
    tipo: ['Agua'],
    habilidades: ['Nado Rápido', 'Francotirador'],
    habitat: 'Mar',
    hp: 30,
    ataque: 40,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png',
  },
  {
    id: 117,
    nombre: 'Seadra',
    tipo: ['Agua'],
    habilidades: ['Punto Tóxico', 'Francotirador'],
    habitat: 'Mar',
    hp: 55,
    ataque: 65,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png',
  },
  {
    id: 118,
    nombre: 'Goldeen',
    tipo: ['Agua'],
    habilidades: ['Nado Rápido', 'Velo Agua'],
    habitat: 'Mar',
    hp: 45,
    ataque: 67,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png',
  },
  {
    id: 119,
    nombre: 'Seaking',
    tipo: ['Agua'],
    habilidades: ['Nado Rápido', 'Velo Agua'],
    habitat: 'Mar',
    hp: 80,
    ataque: 92,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png',
  },
  {
    id: 120,
    nombre: 'Staryu',
    tipo: ['Agua'],
    habilidades: ['Cura Natural', 'Iluminación'],
    habitat: 'Mar',
    hp: 30,
    ataque: 45,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png',
  },
  {
    id: 121,
    nombre: 'Starmie',
    tipo: ['Agua', 'Psíquico'],
    habilidades: ['Cura Natural', 'Iluminación'],
    habitat: 'Mar',
    hp: 60,
    ataque: 75,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png',
  },
  {
    id: 129,
    nombre: 'Magikarp',
    tipo: ['Agua'],
    habilidades: ['Cobardía'],
    habitat: 'Mar',
    hp: 20,
    ataque: 10,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png',
  },
  {
    id: 130,
    nombre: 'Gyarados',
    tipo: ['Agua', 'Volador'],
    habilidades: ['Intimidación', 'Autoestima'],
    habitat: 'Mar',
    hp: 95,
    ataque: 125,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
  },
  {
    id: 131,
    nombre: 'Lapras',
    tipo: ['Agua', 'Hielo'],
    habilidades: ['Absorbe Agua', 'Caparazón'],
    habitat: 'Mar',
    hp: 130,
    ataque: 85,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png',
  },
  {
    id: 134,
    nombre: 'Vaporeon',
    tipo: ['Agua'],
    habilidades: ['Absorbe Agua', 'Hidratación'],
    habitat: 'Mar',
    hp: 130,
    ataque: 65,
    color: '#6390F0',
    imagen:
      'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png',
  },
  // --- MÁS TIERRA (Añadir a la sección de Tierra) ---
  { id: 330, nombre: 'Flygon', tipo: ['Tierra', 'Dragón'], habilidades: ['Levitación'], habitat: 'Tierra', hp: 80, ataque: 100, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/330.png' },
  { id: 260, nombre: 'Swampert', tipo: ['Agua', 'Tierra'], habilidades: ['Torrente', 'Humedad'], habitat: 'Tierra', hp: 100, ataque: 110, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/260.png' },
  { id: 340, nombre: 'Whiscash', tipo: ['Agua', 'Tierra'], habilidades: ['Anticipación', 'Despiste'], habitat: 'Tierra', hp: 110, ataque: 78, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/340.png' },
  { id: 464, nombre: 'Rhyperior', tipo: ['Tierra', 'Roca'], habilidades: ['Pararrayos', 'Solid Rock'], habitat: 'Tierra', hp: 115, ataque: 140, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/464.png' },
  { id: 472, nombre: 'Gliscor', tipo: ['Tierra', 'Volador'], habilidades: ['Corte Fuerte', 'Velo Arena'], habitat: 'Tierra', hp: 75, ataque: 95, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/472.png' },
  { id: 473, nombre: 'Mamoswine', tipo: ['Hielo', 'Tierra'], habilidades: ['Despiste', 'Sebo'], habitat: 'Tierra', hp: 110, ataque: 130, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/473.png' },
  { id: 552, nombre: 'Krokorok', tipo: ['Tierra', 'Siniestro'], habilidades: ['Intimidación', 'Autoestima'], habitat: 'Tierra', hp: 60, ataque: 82, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/552.png' },
  { id: 553, nombre: 'Krookodile', tipo: ['Tierra', 'Siniestro'], habilidades: ['Intimidación', 'Autoestima'], habitat: 'Tierra', hp: 95, ataque: 117, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/553.png' },
  { id: 618, nombre: 'Stunfisk', tipo: ['Tierra', 'Eléctrico'], habilidades: ['Electricidad Estática', 'Flexibilidad'], habitat: 'Tierra', hp: 109, ataque: 66, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/618.png' },
  { id: 718, nombre: 'Zygarde', tipo: ['Dragón', 'Tierra'], habilidades: ['Rompeaura'], habitat: 'Tierra', hp: 108, ataque: 100, color: '#E2BF65', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/718.png' },

  // --- MÁS MAR (Añadir a la sección de Mar) ---
  { id: 138, nombre: 'Omanyte', tipo: ['Roca', 'Agua'], habilidades: ['Caparazón', 'Nado Rápido'], habitat: 'Mar', hp: 35, ataque: 40, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png' },
  { id: 139, nombre: 'Omastar', tipo: ['Roca', 'Agua'], habilidades: ['Caparazón', 'Nado Rápido'], habitat: 'Mar', hp: 70, ataque: 60, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png' },
  { id: 140, nombre: 'Kabuto', tipo: ['Roca', 'Agua'], habilidades: ['Armadura Batalla', 'Nado Rápido'], habitat: 'Mar', hp: 30, ataque: 80, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png' },
  { id: 141, nombre: 'Kabutops', tipo: ['Roca', 'Agua'], habilidades: ['Armadura Batalla', 'Nado Rápido'], habitat: 'Mar', hp: 60, ataque: 115, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png' },
  { id: 184, nombre: 'Azumarill', tipo: ['Agua', 'Hada'], habilidades: ['Potencia', 'Sebo'], habitat: 'Mar', hp: 100, ataque: 50, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/184.png' },
  { id: 245, nombre: 'Suicune', tipo: ['Agua'], habilidades: ['Presión', 'Foco Interno'], habitat: 'Mar', hp: 100, ataque: 75, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/245.png' },
  { id: 320, nombre: 'Wailmer', tipo: ['Agua'], habilidades: ['Velo Agua', 'Despiste'], habitat: 'Mar', hp: 130, ataque: 70, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/320.png' },
  { id: 321, nombre: 'Wailord', tipo: ['Agua'], habilidades: ['Velo Agua', 'Despiste'], habitat: 'Mar', hp: 170, ataque: 90, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/321.png' },
  { id: 382, nombre: 'Kyogre', tipo: ['Agua'], habilidades: ['Llovizna'], habitat: 'Mar', hp: 100, ataque: 100, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png' },
  { id: 489, nombre: 'Phione', tipo: ['Agua'], habilidades: ['Hidratación'], habitat: 'Mar', hp: 80, ataque: 80, color: '#6390F0', imagen: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/489.png' }
];
